const sizeFactor = 1;
export const planets = [
    {
        name: "Mercury",
        radius: 1.2 * 5,
        texture: "/textures/mercury/mercury.jpg",
        yPush: -0.17,
        position: [1.5, 0, -3.6],
        size: 0.2 * sizeFactor - 1,
    },
    {
        name: "Venus",
        radius: 1.8 * 5.5,
        texture: "/textures/venus/venus.jpg",
        yPush: 0,
        position: [3.5, 0, -4],
        size: 0.48 * sizeFactor,
    },
    {
        name: "Mars",
        radius: 3.2 * 6,
        texture: "/textures/mars/mars.jpg",
        yPush: 0,
        position: [-7.6, 0, -6],
        size: 0.27 * sizeFactor,
    },
    {
        name: "Jupiter",
        radius: 4.2 * 6,
        texture: "/textures/jupiter/jupiter.jpg",
        yPush: 0,
        position: [26, 0, -5],
        size: 5 * sizeFactor,
    },
    {
        name: "Saturn",
        radius: 5.4 * 6,
        texture: "/textures/saturn/saturn.jpg",
        yPush: -1.2,
        position: [40.7, 0, 30],
        size: 4.5 * sizeFactor + 4,
    },
    {
        name: "Uranus",
        radius: 7.0 * 6,
        texture: "/textures/uranus/uranus.jpg",
        yPush: -1.3,
        position: [0, 0, 92],
        size: 2 * sizeFactor + 4,
    },
    {
        name: "Neptune",
        radius: 8.0 * 6,
        texture: "/textures/neptune/neptune.jpg",
        yPush: 1 - 1.36,
        position: [-152 - 0.1, 0, 0],
        size: 1.9 * sizeFactor,
    },
];